name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
          working-directory: ./foxglove
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - run: git lfs pull
      - name: run tests
        run:  make test
